# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bomhub
email: simon
description: An index of BOMs and build guides for synth DIY builders.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bomhub.github.io/" # the base hostname & protocol for your site
twitter_username: 
github_username:  bomhub

# Build settings
markdown: kramdown
